# Discord Specific Settings
discord:
  token: "DISCORD_BOT_TOKEN"
  send_time: "16"
  owner: "DISCORD_USER_ID"
  guild: "DISCORD_GUILD_ID"
  self: "DISCORD_BOT_USER_ID"
  trigger: "TRIGGER_CHARACTER"

# Database Configurations
database:
  ip: "localhost"
  db_username: "DB_MASTER_USERNAME"
  db_password: "DB_MASTER_PASSWORD"
